### PR TITLE
SLI-71 Open user security setup page from SonarQube server configuration

### PR DESCRIPTION
**Pull request by dbmeneses**

### CODE REVIEW

**Comment by SonarTech** [comment]
SonarQube analysis reported 2 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [SonarQubeServerEditor.java#L58](https://github.com/SonarSource/sonarlint-intellij/blob/3f1f865dbea93a1ae78f83cc25f6cd57bf3e16fa/src/main/java/org/sonarlint/intellij/config/global/SonarQubeServerEditor.java#L58): Remove this unused "LOGGER" private field. [rule](https://dory.sonarsource.com/sonarqube/coding_rules#rule_key=squid%3AS1068)
1. MAJOR [SonarQubeServerEditor.java#L94](https://github.com/SonarSource/sonarlint-intellij/blob/3f1f865dbea93a1ae78f83cc25f6cd57bf3e16fa/src/main/java/org/sonarlint/intellij/config/global/SonarQubeServerEditor.java#L94): Protected method '<init>(...)' is never used. [rule](https://dory.sonarsource.com/sonarqube/coding_rules#rule_key=squid%3AUnusedProtectedMethod)

**Comment by henryju** [comment]
LGTM. Does it mean we can drop the create token feature from SL core ?

**Comment by dbmeneses** [comment]
@henryju yes, we can drop it. A nice but very short living feature..

**Comment by henryju** [comment]
:)

**Pull request merged**
