### PR TITLE
SLI-693 Update embedded CFamily analyzer to 6.32.0.44918

### PR DESCRIPTION
**Pull request by mpaladin**

### CODE REVIEW

**Review by damien-urruty-sonarsource — APPROVED** [review]

**Comment by mpaladin** [comment]
@henryju this version removes the use of legacy keys in CFamily plugin, is there any logic in `sonarlint-intellij` that should be modified?

**Comment by damien-urruty-sonarsource** [comment]
@mpaladin I missed this change, it was maybe a bit prematurate to merge, my bad

**Comment by damien-urruty-sonarsource** [comment]
I double checked in SLCORE and we should be safe :+1:

**Comment by henryju** [comment]
You mean that thanks to the deprecatedRuleKeys attribute of rules definition, there will be a mapping of old -> new rule keys? Does it work also in connected mode?

**Pull request merged**
