### PR TITLE
Added settings to filter issues by severity and type

### PR DESCRIPTION
**Pull request by Zhabha**
Severity filtering might be useful when working on old projects, as there's usually quite a lot of issues, so it might be useful to filter out only the most critical ones and not be flooded with the low severity ones.

### CODE REVIEW

**Comment by Zhabha** [comment]
rebased onto latest master

**Comment by rhanton** [comment]
Is anyone working on fixing the conflicts for this? I had this issue yesterday and it was incredibly annoying (i.e. no ability to select-all, select-none, select by category).

**Comment by Zhabha** [comment]
> Is anyone working on fixing the conflicts for this? I had this issue yesterday and it was incredibly annoying (i.e. no ability to select-all, select-none, select by category).

My teams stopped using the plug-in altogether :/ so there's no need for this kind of update from my side anymore, nor I have much time these days to tinker with it.
So unless anyone wants this badly, feel free to reject this PR.

**Comment by huzhongchun0918** [comment]
> > Is anyone working on fixing the conflicts for this? I had this issue yesterday and it was incredibly annoying (i.e. no ability to select-all, select-none, select by category).
> 
> My teams stopped using the plug-in altogether :/ so there's no need for this kind of update from my side anymore, nor I have much time these days to tinker with it.
> So unless anyone wants this badly, feel free to reject this PR.

yes,I need it, too.

**Comment by janos-ss** [comment]
Thank you @Zhabha for this contribution. I think it's a nice idea. However, providing great UX, as well as a usage pattern that is in line with our long-term vision is no simple matter, and it takes careful planning on our part. I created a [ticket](https://jira.sonarsource.com/browse/SLI-329) that I believe reflects the intention behind your suggested feature (and then generalized it some). If and when we handle this, I'm not sure if we'll be able to use this contribution, but we'll certainly keep it in mind. I close this PR now.

Lastly, when it comes to fixing quality issues in old code, we have a certain philosophy we dub the ["water leak paradigm"](https://docs.sonarqube.org/latest/user-guide/fixing-the-water-leak/). I think it has some relevance in the context of your suggestion, and I hope you'll find it useful.

**Pull request closed without merging**
